__author__ = 'anthonymendoza'

la_county_precipitation_data =  "/Users/anthonymendoza/Documents/seed_consulting_group/seedLA_HTB_2015_project/water_sustainability/data_store/los_angeles_county_data_store/la_county_precipiatation_data_national_weather_service.csv"
