# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=5, null=True)),
                ('country_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('county_code', models.IntegerField(default=0)),
                ('active_status', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroundWaterWell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, null=True)),
                ('site_code', models.CharField(max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=75, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=75, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('units', models.CharField(max_length=100, null=True)),
                ('source', models.CharField(max_length=500, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='water_store.County')),
            ],
        ),
        migrations.CreateModel(
            name='ReclamationPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('treatment_type', models.CharField(max_length=100, null=True)),
                ('capacity_MGD', models.DecimalField(decimal_places=4, max_digits=75, null=True)),
                ('water_producedMGD', models.DecimalField(decimal_places=4, max_digits=75, null=True)),
                ('date_recorded', models.DateTimeField(null=True)),
                ('water_producedAFY', models.DecimalField(decimal_places=4, max_digits=75, null=True)),
                ('operation_management_costAFY', models.CharField(max_length=20, null=True)),
                ('operation_management_costY', models.CharField(max_length=20, null=True)),
                ('water_reusedMGD', models.DecimalField(decimal_places=4, max_digits=75, null=True)),
                ('water_reusedAFY', models.DecimalField(decimal_places=4, max_digits=75, null=True)),
                ('reuse_sites', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('reuse_sites_sizeACRES', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='water_store.County')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('state_code', models.IntegerField(default=0)),
                ('country_internal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='water_store.Country')),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='state_internal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='water_store.State'),
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together=set([('name', 'abbreviation')]),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set([('name', 'abbreviation')]),
        ),
        migrations.AlterUniqueTogether(
            name='county',
            unique_together=set([('name', 'state_internal')]),
        ),
    ]
