# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_store', '0002_auto_20160131_1905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set([]),
        ),
    ]
