# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_store', '0003_auto_20160131_1906'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='country',
            unique_together=set([('name', 'abbreviation')]),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set([('name', 'abbreviation')]),
        ),
    ]
