# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water_store', '0004_auto_20160131_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evapotranspiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, null=True)),
                ('site_code', models.CharField(max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=75, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=75, null=True)),
                ('date', models.CharField(max_length=50, null=True)),
                ('active', models.BooleanField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('units', models.CharField(max_length=100, null=True)),
                ('source', models.CharField(max_length=500, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='water_store.County')),
            ],
        ),
        migrations.CreateModel(
            name='Precipitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, null=True)),
                ('site_code', models.CharField(max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=75, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=75, null=True)),
                ('date', models.CharField(max_length=50, null=True)),
                ('active', models.BooleanField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('units', models.CharField(max_length=100, null=True)),
                ('source', models.CharField(max_length=500, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='water_store.County')),
            ],
        ),
        migrations.CreateModel(
            name='SpreadingGround',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=75, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=75, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('percolation', models.CharField(max_length=75, null=True)),
                ('storage', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('units', models.CharField(max_length=100, null=True)),
                ('source', models.CharField(max_length=500, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='water_store.County')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, null=True)),
                ('site_code', models.CharField(max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=75, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=75, null=True)),
                ('date', models.CharField(max_length=50, null=True)),
                ('active', models.BooleanField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('units', models.CharField(max_length=100, null=True)),
                ('source', models.CharField(max_length=500, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='water_store.County')),
            ],
        ),
    ]
